export const FETCH_PHONES = "FETCH_PHONES";
export const FETCH_PHONES_API_START = "FETCH_PHONES_API_START";
export const FETCH_PHONES_API_FINISHED = "FETCH_PHONES_API_FINISHED";
export const SET_PHONES = "SET_PHONES";